//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VitaminD.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VitaminD.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AboutHeader {
            get {
                return ResourceManager.GetString("AboutHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to turn it on.
        /// </summary>
        public static string ActiveReminderLabel {
            get {
                return ResourceManager.GetString("ActiveReminderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vitamin d.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VITAMIN D.
        /// </summary>
        public static string ApplicationTitleUpper {
            get {
                return ResourceManager.GetString("ApplicationTitleUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pause.
        /// </summary>
        public static string ButtonActionPauseText {
            get {
                return ResourceManager.GetString("ButtonActionPauseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resume.
        /// </summary>
        public static string ButtonActionResumeText {
            get {
                return ResourceManager.GetString("ButtonActionResumeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start monitor.
        /// </summary>
        public static string ButtonActionStartText {
            get {
                return ResourceManager.GetString("ButtonActionStartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cereal.
        /// </summary>
        public static string CerTitle {
            get {
                return ResourceManager.GetString("CerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stop alarm.
        /// </summary>
        public static string CloseAlarm {
            get {
                return ResourceManager.GetString("CloseAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The body naturally synthesize vitamin D when exposed to sunlight. All you need for a week’s worth of vitamin D is for about 20 minutes in the sun. 
        ///VitaminD app will help you with a simple way to keep you posted about when you need to go to outside and get more sunlight..
        /// </summary>
        public static string Disclaimer {
            get {
                return ResourceManager.GetString("Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eggs.
        /// </summary>
        public static string EggTitle {
            get {
                return ResourceManager.GetString("EggTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to main.
        /// </summary>
        public static string MainHeader {
            get {
                return ResourceManager.GetString("MainHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to milk.
        /// </summary>
        public static string MilkTitle {
            get {
                return ResourceManager.GetString("MilkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mushroom.
        /// </summary>
        public static string MusTitle {
            get {
                return ResourceManager.GetString("MusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate and Review .
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplication version: 1.1.
        /// </summary>
        public static string Release {
            get {
                return ResourceManager.GetString("Release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my reminders.
        /// </summary>
        public static string ReminderList {
            get {
                return ResourceManager.GetString("ReminderList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reminder.
        /// </summary>
        public static string ReminderView {
            get {
                return ResourceManager.GetString("ReminderView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ricotta.
        /// </summary>
        public static string RicTitle {
            get {
                return ResourceManager.GetString("RicTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to salmon.
        /// </summary>
        public static string SalTitle {
            get {
                return ResourceManager.GetString("SalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Runtime Property Value.
        /// </summary>
        public static string SampleProperty {
            get {
                return ResourceManager.GetString("SampleProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like fortified milk, fortified cereal provides a more balanced meal than a Vitamin D supplement. The amount of Vitamin D in cereals varies widely by brand and type, though, so read the label carefully..
        /// </summary>
        public static string SourceCer {
            get {
                return ResourceManager.GetString("SourceCer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two large eggs have about one-tenth of a daily dose of Vitamin D. Eggs from truly free-range chickens, like those many are raising in backyards these days, are often more tasty and nutritious than the factory farmed kind; unfortunately, the free-range label on eggs is virtually meaningless..
        /// </summary>
        public static string SourceEgg {
            get {
                return ResourceManager.GetString("SourceEgg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fortified milk has about one-fifth a day&apos;s worth of Vitamin D (whole milk has more than skim)..
        /// </summary>
        public static string SourceMilk {
            get {
                return ResourceManager.GetString("SourceMilk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mushrooms can have a significant amount of Vitamin D, but the amount varies widely by type. Shiitake mushrooms (pictured) have 45 iu – about one-thirteenth of a daily serving of Vitamin D. White mushrooms, on the other hand, have just 5 iu.
        /// </summary>
        public static string SourceMus {
            get {
                return ResourceManager.GetString("SourceMus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ricotta cheese stands out among cheeses for its relatively high Vitamin D content. 
        ///With 25 iu of Vitamin D, it would still take about 24 servings to get your daily dose 
        ///solely from ricotta cheese (not recommended). That said, ricotta has about five times as much Vitamin D as most other cheeses..
        /// </summary>
        public static string SourceRic {
            get {
                return ResourceManager.GetString("SourceRic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salmon has by far the most Vitamin D of any food (and wild salmon has much more than farmed salmon, which unfortunately is cheaper and easier to find). Half a fillet of sockeye salmon has more than 1,400 iu of Vitamin D – more than twice as much as most people need in a day..
        /// </summary>
        public static string SourceSal {
            get {
                return ResourceManager.GetString("SourceSal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sources.
        /// </summary>
        public static string SourcesHeader {
            get {
                return ResourceManager.GetString("SourcesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunlight is the best and only natural source of vitamin D. The body naturally synthesize vitamin D when exposed to sunlight. All you need for a week’s worth of vitamin D is for about 20 minutes in the sun. It is a balancing exercise between not enough and too much sunshine. You do not want to burn or over-expose your skin..
        /// </summary>
        public static string SourceSun {
            get {
                return ResourceManager.GetString("SourceSun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A serving of tuna has a healthy dose of Vitamin D - more than one-third of a daily dose. Light tuna in oil has the most Vitamin D. (Light tuna in water has about one-fourth of a daily dose, while white tuna has about one-tenth. Light tuna also has less mercury than white tuna, making it a safer choice.).
        /// </summary>
        public static string SourceTun {
            get {
                return ResourceManager.GetString("SourceTun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to source.
        /// </summary>
        public static string SourceView {
            get {
                return ResourceManager.GetString("SourceView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to turn it off.
        /// </summary>
        public static string StopReminderLabel {
            get {
                return ResourceManager.GetString("StopReminderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulation!!! 
        ///You reached the minimum time of exposure to Sunlight recommended daily..
        /// </summary>
        public static string SunlightExposure {
            get {
                return ResourceManager.GetString("SunlightExposure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add reminder.
        /// </summary>
        public static string SunlightReminder {
            get {
                return ResourceManager.GetString("SunlightReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sunlight timer.
        /// </summary>
        public static string SunlightTimer {
            get {
                return ResourceManager.GetString("SunlightTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sunlight.
        /// </summary>
        public static string SunTitle {
            get {
                return ResourceManager.GetString("SunTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep tracking your exposure to sunlight. After 20 minutes, VintaminD will alert you about your goal reached..
        /// </summary>
        public static string TimerAbout {
            get {
                return ResourceManager.GetString("TimerAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to timer.
        /// </summary>
        public static string TimerView {
            get {
                return ResourceManager.GetString("TimerView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tuna.
        /// </summary>
        public static string TunTitle {
            get {
                return ResourceManager.GetString("TunTitle", resourceCulture);
            }
        }
    }
}
